import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const installScript = fs.readFileSync(new URL('../../install.sh', import.meta.url), 'utf8')
const httpsGuide = fs.readFileSync(new URL('../../docs/deployment/https-screen-share.md', import.meta.url), 'utf8')

test('install.sh 支持交互式域名、HTTP/HTTPS 与 Nginx webroot 证书配置', () => {
  assert.match(installScript, /是否配置域名/)
  assert.match(installScript, /是否启用 HTTPS/)
  assert.match(installScript, /HTTPS_PORT=\"443\"/)
  assert.match(installScript, /请输入 HTTPS 端口/)
  assert.match(installScript, /read -r -p \"请输入域名/)
  assert.match(installScript, /APP_PORT=.*3002/)
  assert.match(installScript, /APP_PORT=.*3002/)
  assert.match(installScript, /install_nginx_stack/)
  assert.match(installScript, /command -v nginx/)
  assert.match(installScript, /apt-get install -y nginx/)
  assert.match(installScript, /validate_existing_nginx_config/)
  assert.match(installScript, /describe_nginx_site_status/)
  assert.match(installScript, /describe_certificate_status/)
  assert.match(installScript, /ACME_WEBROOT_BASE/)
  assert.match(installScript, /acme_webroot_path\(\)/)
  assert.match(installScript, /certbot certonly --webroot/)
  assert.match(installScript, /\.well-known\/acme-challenge\//)
  assert.doesNotMatch(installScript, /python3-certbot-nginx/)
  assert.doesNotMatch(installScript, /certbot --nginx -d/)
  assert.match(installScript, /select_https_port\(\)/)
  assert.match(installScript, /verify_https_listener\(\)/)
  assert.match(installScript, /port_in_use\(\)/)
  assert.match(installScript, /port_used_by_nginx\(\)/)
  assert.match(installScript, /configure_nginx/)
  assert.match(installScript, /sites-available/)
  assert.match(installScript, /systemctl reload nginx|\$SUDO systemctl reload nginx/)
  assert.doesNotMatch(installScript, /install_caddy/)
  assert.match(installScript, /HTTPS 监听端口/)
  assert.doesNotMatch(installScript, /configure_caddy/)
})

test('HTTPS 部署文档说明 install.sh 使用 certbot webroot 配置 Nginx', () => {
  assert.match(httpsGuide, /install\.sh/)
  assert.match(httpsGuide, /是否配置域名/)
  assert.match(httpsGuide, /是否启用 HTTPS/)
  assert.match(httpsGuide, /443/)
  assert.match(httpsGuide, /443.*被.*占用|HTTPS.*端口/)
  assert.match(httpsGuide, /npm run serve/)
  assert.match(httpsGuide, /Nginx/)
  assert.match(httpsGuide, /certbot/)
  assert.match(httpsGuide, /webroot/)
  assert.match(httpsGuide, /\.well-known\/acme-challenge\//)
  assert.doesNotMatch(httpsGuide, /python3-certbot-nginx/)
  assert.doesNotMatch(httpsGuide, /certbot --nginx -d/)
  assert.doesNotMatch(httpsGuide, /Caddy（无需 Nginx）/)
})
